<script setup>
    
</script>

<template>
    <div>
        <div class="loadingio-spinner-dual-ball-2by998twmg8">
            <div class="ldio-yzaezf3dcmj">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>  
</template>

<style>
   @keyframes ldio-yzaezf3dcmj-o {
       0% {
           opacity: 1;
           transform: translate(0 0)
       }

       49.99% {
           opacity: 1;
           transform: translate(80px, 0)
       }

       50% {
           opacity: 0;
           transform: translate(80px, 0)
       }

       100% {
           opacity: 0;
           transform: translate(0, 0)
       }
   }

   @keyframes ldio-yzaezf3dcmj {
       0% {
           transform: translate(0, 0)
       }

       50% {
           transform: translate(80px, 0)
       }

       100% {
           transform: translate(0, 0)
       }
   }

   .ldio-yzaezf3dcmj div {
       position: absolute;
       width: 40px;
       height: 40px;
       border-radius: 50%;
       top: 30px;
       left: 10px;
   }

   .ldio-yzaezf3dcmj div:nth-child(1) {
       background: #e90c59;
       animation: ldio-yzaezf3dcmj 1s linear infinite;
       animation-delay: -0.5s;
   }

   .ldio-yzaezf3dcmj div:nth-child(2) {
       background: #46dff0;
       animation: ldio-yzaezf3dcmj 1s linear infinite;
       animation-delay: 0s;
   }

   .ldio-yzaezf3dcmj div:nth-child(3) {
       background: #e90c59;
       animation: ldio-yzaezf3dcmj-o 1s linear infinite;
       animation-delay: -0.5s;
   }

   .loadingio-spinner-dual-ball-2by998twmg8 {
       width: 150px;
       height: 100px;
       display: inline-block;
       overflow: hidden;
       background: #efeeee;
   }

   .ldio-yzaezf3dcmj {
       width: 100%;
       height: 100%;
       position: relative;
       transform: translateZ(0) scale(1);
       backface-visibility: hidden;
       transform-origin: 0 0;
       /* see note above */
   }

   .ldio-yzaezf3dcmj div {
       box-sizing: content-box;
   }

   /* [ldio] generated by https://loading.io */
</style>